#!/usr/bin/env bash
#
# Fresh-install (or update) the HeaterMeter host daemon on Raspberry Pi OS.
#
# Idempotent: safe to re-run to refresh dependencies or the systemd unit.
# Creates a venv, installs the package + runtime extras, generates a systemd
# unit for the current user/paths, and enables the service.
#
#   bash deploy/install.sh                 # defaults: /dev/serial0, port 8080
#   SERIAL=/dev/ttyAMA0 PORT=8080 bash deploy/install.sh
#
# Prereqs (do these first):
#   1. Free the serial UART so the board can talk to the Pi:
#        see deploy/uart-setup.md
#   2. Leave SPI DISABLED for normal operation. SPI is only needed to flash the
#        AVR firmware, and while it is on the LCD will not work (the AVR drives
#        the LCD over the same SPI pins). See FIRMWARE-UPDATE.md.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USER_NAME="${SUDO_USER:-$USER}"
PYBIN="${PYBIN:-python3}"
VENV="$REPO/.venv"
DB="$REPO/data/hm.sqlite"
PORT="${PORT:-8080}"
SERIAL="${SERIAL:-/dev/serial0}"
UNIT="/etc/systemd/system/heatermeterd.service"
# In-software firmware updater paths.
SPOOL="$REPO/data/firmware/spool"               # group-writable IPC handoff
FWDIR="/usr/local/share/heatermeter/firmware"   # trusted, root-owned images
FLASH_BIN="/usr/local/sbin/hm-flash"
FLASH_PATH_UNIT="/etc/systemd/system/hm-flash.path"
FLASH_SVC_UNIT="/etc/systemd/system/hm-flash.service"
# In-software host-app updater paths.
HU_SPOOL="$REPO/data/hostupdate/spool"          # IPC handoff with hm-update
HU_STAGING="$REPO/data/hostupdate/staging"      # daemon downloads land here
HU_BIN="/usr/local/sbin/hm-update"
HU_PATH_UNIT="/etc/systemd/system/hm-update.path"
HU_SVC_UNIT="/etc/systemd/system/hm-update.service"

echo "HeaterMeter installer"
echo "  repo:   $REPO"
echo "  user:   $USER_NAME"
echo "  serial: $SERIAL    port: $PORT"
echo "  db:     $DB"
echo

# 1. Python venv + runtime dependencies (pyserial + fastapi + uvicorn + paho).
echo ">>> Creating venv and installing dependencies..."
"$PYBIN" -m venv "$VENV"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -e "$REPO/backend[pi]"
mkdir -p "$REPO/data"

# 2. systemd unit, generated for this user and these paths.
echo ">>> Installing systemd unit at $UNIT (needs sudo)..."
sudo tee "$UNIT" >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=HeaterMeter host daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER_NAME
Group=dialout
WorkingDirectory=$REPO/backend
ExecStart=$VENV/bin/python -m heatermeterd.main --serial $SERIAL --port $PORT --db $DB
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now heatermeterd

# 3. In-software firmware updater. Installs the trusted (root-owned) image set
#    the helper will accept, the root flash helper, the group-writable IPC
#    spool, and the path-activated root unit. The daemon (unprivileged) writes
#    a request into the spool; systemd then runs the helper as root to do the
#    flash. The helper toggles the SPI overlay at runtime (no reboot) and
#    re-inits the LCD afterwards. See deploy/hm-flash + FIRMWARE-UPDATE.md.
echo ">>> Installing the firmware updater (helper, images, units; needs sudo)..."
# jq is required by the flash helper. Refresh the package index first so the
# install does not fail on a stale cache.
if ! command -v jq >/dev/null 2>&1; then
  sudo apt-get update
  sudo apt-get install -y jq
fi
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required but could not be installed"; exit 1; }

# Trusted image set: root-owned so the daemon user cannot swap a hex (the
# sha256 manifest check gates flashing regardless, but defence in depth).
sudo install -d -m 0755 -o root -g root "$FWDIR"
sudo install -m 0644 -o root -g root "$REPO"/firmware/heatermeter-*.hex "$FWDIR/"
sudo install -m 0644 -o root -g root "$REPO/firmware/manifest.json" "$FWDIR/"

# The privileged helper.
sudo install -m 0755 -o root -g root "$REPO/deploy/hm-flash" "$FLASH_BIN"

# Group-writable spool (setgid so helper-created files inherit the group the
# daemon can read). Owned by the daemon user, group dialout.
install -d -m 2770 "$SPOOL"
chgrp dialout "$SPOOL" 2>/dev/null || sudo chgrp dialout "$SPOOL"

# Path unit (watches request.json) + the oneshot root service, generated with
# this host's spool path.
sudo tee "$FLASH_PATH_UNIT" >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=Watch for a HeaterMeter firmware flash request

[Path]
PathChanged=$SPOOL/request.json
Unit=hm-flash.service

[Install]
WantedBy=multi-user.target
EOF

sudo tee "$FLASH_SVC_UNIT" >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=HeaterMeter AVR flash (root, oneshot)

[Service]
Type=oneshot
Environment=HM_FLASH_SPOOL=$SPOOL
Environment=HM_FLASH_FWDIR=$FWDIR
Environment=HM_FLASH_GROUP=dialout
ExecStart=$FLASH_BIN
TimeoutStartSec=240
EOF

# System poweroff helper + its path-activated root unit (Settings -> System).
sudo install -m 0755 -o root -g root "$REPO/deploy/hm-power" /usr/local/sbin/hm-power
sudo tee /etc/systemd/system/hm-power.path >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=Watch for a HeaterMeter poweroff request

[Path]
PathChanged=$SPOOL/poweroff.request
Unit=hm-power.service

[Install]
WantedBy=multi-user.target
EOF
sudo tee /etc/systemd/system/hm-power.service >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=HeaterMeter system poweroff (root, oneshot)

[Service]
Type=oneshot
Environment=HM_POWER_SPOOL=$SPOOL
ExecStart=/usr/local/sbin/hm-power
EOF

# 4. In-software host-app updater. Installs the root update helper, the IPC
#    spool + staging dir (owned by the daemon user), and the path-activated root
#    unit. The daemon downloads + sha-verifies a release from the operator's
#    configured manifest URL, then writes a request; systemd runs the helper as
#    root to swap the code + frontend and restart the service, with a post-restart
#    health check that auto-rolls-back a bad build. See deploy/hm-update.
echo ">>> Installing the host-app updater (helper, units; needs sudo)..."
sudo install -m 0755 -o root -g root "$REPO/deploy/hm-update" "$HU_BIN"

# Spool (IPC) + staging (downloads). Owned by the daemon user; group dialout so
# helper-written result files inherit a group the daemon can read.
install -d -m 2770 "$HU_SPOOL"
install -d -m 0775 "$HU_STAGING"
chgrp dialout "$HU_SPOOL" 2>/dev/null || sudo chgrp dialout "$HU_SPOOL"

sudo tee "$HU_PATH_UNIT" >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=Watch for a HeaterMeter host-app update request

[Path]
# Level-triggered (PathExists, not PathChanged): host updates can be back-to-back
# and an edge trigger drops a request written during a prior helper run. The
# helper consumes request.json by renaming it, so this clears and never loops.
PathExists=$HU_SPOOL/request.json
Unit=hm-update.service

[Install]
WantedBy=multi-user.target
EOF

sudo tee "$HU_SVC_UNIT" >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=HeaterMeter host-app update (root, oneshot)

[Service]
Type=oneshot
Environment=HM_UPDATE_SPOOL=$HU_SPOOL
Environment=HM_UPDATE_INSTALL_ROOT=$REPO
Environment=HM_UPDATE_USER=$USER_NAME
Environment=HM_UPDATE_SERVICE=heatermeterd
Environment=HM_UPDATE_PORT=$PORT
ExecStart=$HU_BIN
TimeoutStartSec=240
EOF

# 5. Nightly backups: DB snapshot + configs into <repo>/backups, rotated.
echo ">>> Installing the nightly backup timer (needs sudo)..."
sudo install -m 0755 -o root -g root "$REPO/deploy/hm-backup.sh" /usr/local/sbin/hm-backup
sudo tee /etc/systemd/system/hm-backup.service >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=HeaterMeter nightly backup (DB snapshot + configs)

[Service]
Type=oneshot
User=$USER_NAME
Environment=HM_BACKUP_REPO=$REPO
ExecStart=/usr/local/sbin/hm-backup
EOF
sudo tee /etc/systemd/system/hm-backup.timer >/dev/null <<EOF
# Generated by deploy/install.sh
[Unit]
Description=Run the HeaterMeter backup nightly

[Timer]
OnCalendar=*-*-* 03:30:00
RandomizedDelaySec=600
Persistent=true

[Install]
WantedBy=timers.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now hm-flash.path
sudo systemctl enable --now hm-power.path
sudo systemctl enable --now hm-update.path
sudo systemctl enable --now hm-backup.timer

echo
echo ">>> Done. The daemon is enabled and running."
echo "    Dashboard:  http://<pi-address>:$PORT/"
echo "    Live logs:  journalctl -u heatermeterd -f"
echo "    MQTT/Home Assistant and notifications are configured in the dashboard"
echo "    under Settings -> Integrations (no files to edit)."
echo "    Firmware updates: Settings -> Firmware (the actual flash is a"
echo "    supervised, one-click action; keep the controller powered)."
